name: pcb-bridge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - scipy
  - numpy
  - matplotlib
  - python-multipart
  - pip
  - pip:
    - flask-cors
